#!/usr/bin/env python3
# TODO: write a node that plans crazyflie paths
# for now, just manually plan waypoints and send them to drones
# eventually, use the define and start trajectory part of the high level commander api to get smooth routes
# eventually, subscribe to jackal waypoints and send crazyflies to them

import math
import time
import rospy
from geometry_msgs.msg import PoseStamped
from tf.transformations import quaternion_from_euler

from crazyflies.compute_trajectory import waypoints_to_smooth_trajectory
from crazyflies.reformat_trajectory import cflib_trajectory_to_topic_msg
from crazyflies.msg import Trajectory
from std_srvs.srv import Trigger, TriggerRequest

class CrazyfliePlanner:
    def __init__(self):
        self.cf_namespaces = rospy.get_param("~cf_namespaces", ["cf1"])
        self.map_frame = rospy.get_param("~map_frame", "map")
        self._reset_services = {}
        self.cf_waypoint_pubs = {}
        self.cf_trajectory_pubs = {}
        for ns in self.cf_namespaces:
            self.cf_waypoint_pubs[ns] = rospy.Publisher(f'/{ns}/goal', PoseStamped, queue_size=10, latch=True)
            self.cf_trajectory_pubs[ns] = rospy.Publisher(f'/{ns}/trajectory', Trajectory, queue_size=10, latch=True)

        self.reset_all()
        rospy.loginfo('all drones reset')
        # waypoints = [
        #     (0.0, 0.0, 0.5, 0.0),
        #     (0.5, 0.25, 0.5, 0.0),
        #     (1, 1, 0.5, 0),
        #     (1.5, 2.25, 0.5, .4242),
        #     (1, 1, 0.5, 1.7),
        #     (0, 0, 0.5, 0),
        # ]

        waypoints = [
            (0.0, 0.0, 0.5, 0.0),
            (0, 1, 0.5, 0.0),
            (1, 1, 0.5, 0),
            (1, 0, 0.5, .0),
            (0.0, 0.0, 0.5, 0.0),
        ]
        trajectory = waypoints_to_smooth_trajectory(waypoints, segment_time=2.0)
    
        rospy.loginfo("trajectory: "+str(trajectory))

        self.publish_trajectory(self.cf_namespaces[0], trajectory)
        self.publish_trajectory(self.cf_namespaces[1], trajectory)
        self.publish_trajectory(self.cf_namespaces[2], trajectory)
        self.publish_trajectory(self.cf_namespaces[3], trajectory)

        # time.sleep(7)
        # self.send_goal(self.cf_namespaces[0], 1.0, 1.0, 0.0, yaw_deg=180)
        # self.send_goal(self.cf_namespaces[1], 1.0, -1.0, 0.0, yaw_deg=90)
        # self.send_goal(self.cf_namespaces[2], -1.0, 1.0, 0.0, yaw_deg=180)
        # self.send_goal(self.cf_namespaces[3], -1.0, -1.0, 0.0, yaw_deg=90)
        # time.sleep(10)        
        # self.send_goal(self.cf_namespaces[0], 3.0, -2.0, 0.0, yaw_deg=270)
        # self.send_goal(self.cf_namespaces[1], -2.3, 3.95, 0.0, yaw_deg=45)
        # self.send_goal(self.cf_namespaces[2], -3.0, 2.0, 0.0, yaw_deg=270)
        # self.send_goal(self.cf_namespaces[3], -2.3, -3.95, 0.0, yaw_deg=45)
        # time.sleep(10)
        # self.send_goal(self.cf_namespaces[0], 0.58, 0.58, 0.0, yaw_deg=0)
        # self.send_goal(self.cf_namespaces[1], 0.58, -0.58, 0.0, yaw_deg=0)
        # self.send_goal(self.cf_namespaces[2], -0.58, 0.58, 0.0, yaw_deg=0)
        # self.send_goal(self.cf_namespaces[3], -0.58, -0.58, 0.0, yaw_deg=0)
        
    def publish_trajectory(self, ns, cflib_trajectory):
        if ns not in self.cf_trajectory_pubs:
            rospy.logwarn(f"No trajectory publisher for namespace '{ns}'")
            return
        temp = cflib_trajectory_to_topic_msg(cflib_trajectory)
        self.cf_trajectory_pubs[ns].publish(temp)
        rospy.loginfo('Published trajectory with %d pieces to %s',
                    len(cflib_trajectory), ns)


    def send_goal(self, ns, x, y, z, yaw_deg=0.0):
        if ns not in self.cf_waypoint_pubs:
            rospy.logwarn(f"No goal publisher for namespace '{ns}'")
            return

        msg = PoseStamped()

        msg.header.stamp = rospy.Time.now()
        msg.header.frame_id = self.map_frame

        msg.pose.position.x = x
        msg.pose.position.y = y
        msg.pose.position.z = z

        yaw_rad = math.radians(yaw_deg)
        qx, qy, qz, qw = quaternion_from_euler(0.0, 0.0, yaw_rad)

        msg.pose.orientation.x = qx
        msg.pose.orientation.y = qy
        msg.pose.orientation.z = qz
        msg.pose.orientation.w = qw

        self.cf_waypoint_pubs[ns].publish(msg)

        rospy.loginfo(
            f"Sent goal to {ns}: "
            f"x={x:.2f}, y={y:.2f}, z={z:.2f}"
        )

    def _get_reset_service(self, ns):
        if ns not in self._reset_services:
            service_name = f'/{ns}/reset'
            rospy.loginfo(service_name)
            try:
                rospy.wait_for_service(service_name, timeout=10.0)
            except rospy.ROSException as exc:
                raise RuntimeError(f'Unable to contact HLCommand service at {service_name}: {exc}')
            self._reset_services[ns] = rospy.ServiceProxy(service_name, Trigger)
        return self._reset_services[ns]

    def _send_reset_command(self, ns):
        service = self._get_reset_service(ns)
        resp = service()
        if not resp.success:
            raise RuntimeError(resp.message)
        return resp

    def reset_all(self):
        for ns in self.cf_namespaces:
            rospy.loginfo(f'sending reset command to {ns}')
            self._send_reset_command(ns)

def main():
    rospy.init_node('crazyflie_planner')
    CrazyfliePlanner()
    rospy.spin()


if __name__ == '__main__':
    main()